Background location support.
Lyokone/flutterlocation pull request #455
Opened 2020-12-11 11:09 UTC by maciejpigulski

Background mode based on iOS native background location and an Android Service.

This implementation is not based on `ServiceAware` Flutter interface as this one seems to be not yet finalized. 

On iOS we have used native OS support for background location.

On Android general idea was to not to interfere that much with `FlutterLocation.java` code and try to introduce a [Android Service](https://developer.android.com/guide/components/services) wrapper around it so it can be launched in a foreground service. This means that are spaces there to improve probably if this PR is to be accepted.

Background location permissions are verified upon trying to switch into background mode using the introduced `enableBackgroundMode(boolean)` method. There is no separate method to check if background permissions are met like this is done for getting regular location.

Implementation is open for discussion, to merge it fully we would probably need some updates on the `pubspec.yaml` to point to a specific version and not a git repository. 

For now as dependencies are not published on `pub.dev` you can still use the implementation from the publicly available fork.

We wanted to contribute to the project on behalf of Dunning, Kruger & Associates company that invested in adding this functionality. We were using this plugin in our commercial project and needed support of background location and this plugin proved to be one of the most well written ones.

on-behalf-of: @dkna <contact@dka.io>
co-authored-by: arek-zarebski-dka <arkadiusz.zarebski@dka.io>

2020-12-17 19:16 UTC, Lyokone requested changes
Thanks a lot for this great implementation ! It sure will be helpful for a lot of persons 👍

2020-12-17 19:16 UTC, Lyokone commented on location_web/pubspec.yaml
> +      url: git@github.com:DKnA/flutterlocation.git
This would need to be set to the local version, I think 
path: ../location_platform_interface
should do the trick

2020-12-17 19:16 UTC, Lyokone commented on location/pubspec.yaml
> +      url: git@github.com:DKnA/flutterlocation.git
Same as below

2020-12-21 09:16 UTC, maciejpigulski commented on location_web/pubspec.yaml
> +      url: git@github.com:DKnA/flutterlocation.git
Shouldn't `location_platform_interface` be just released as a dependency with a version bumped up to lets say 1.1.0 or so?

2020-12-21 13:45 UTC, Lyokone commented on location_web/pubspec.yaml
> +      url: git@github.com:DKnA/flutterlocation.git
Yes you're right, when I release a new version, I publish `location_platform_interface`. Not sure what should be commited in git ? Probably directly the one with the correct versions ? Even tho it will not work directly. Let's leave the numbered version then.

2020-12-21 14:19 UTC, maciejpigulski commented on location_web/pubspec.yaml
> +      url: git@github.com:DKnA/flutterlocation.git
In the modules `location_platform_interface` and `location_web` I have already updated version numbers according to the template you have picked for earlier releases.

So... I can update dependencies to a numbered version that is for `location_web` it would be 1.0.1: https://github.com/DKnA/flutterlocation/blob/master/location_web/pubspec.yaml and for `location_platform_interface` 1.1.0 https://github.com/DKnA/flutterlocation/blob/master/location_platform_interface/pubspec.yaml

2020-12-23 11:57 UTC, Lyokone commented on location_web/pubspec.yaml
> +      url: git@github.com:DKnA/flutterlocation.git
Yes it's perfect that way thank you 👍

2020-12-23 11:59 UTC, Lyokone approved these changes

2020-12-23 12:16 UTC, merged