Added an enum value LocationAccuracy.reduced
Lyokone/flutterlocation pull request #559
Opened 2021-05-08 18:51 UTC by yixiang

2021-05-10 08:58 UTC, Lyokone requested changes

2021-05-10 08:58 UTC, Lyokone commented on packages/location_platform_interface/lib/src/types.dart
> +
I think we should ensure that it's mapped to a fallback value on Android. Can you do it ? Or I can modify your PR.

2021-05-10 13:54 UTC, yixiang commented on packages/location_platform_interface/lib/src/types.dart
> +
Please add the Android fallback. I'm not familiar with Android side of things. Please also update the documentation on the enum value as you do that. 

Thank you.

2021-06-05 13:37 UTC, Lyokone commented
I have reopened this PR here : https://github.com/Lyokone/flutterlocation/pull/574

2021-06-05 13:37 UTC, closed without merging