Added ability to configure whether the location-manager may pause loc…
Lyokone/flutterlocation pull request #933
Opened 2024-03-07 17:21 UTC by tanvir-ahmed-m4

…ation updates in iOS

2024-03-30 19:56 UTC, bartekpacia requested changes
Hi, thanks for contributing.

Please take a look at comments. Also, I'm curious to learn what's the use-case of this feature. Why do you need it?

2024-03-30 19:56 UTC, bartekpacia commented on packages/location_web/pubspec.yaml
> +    path: ../location_platform_interface/
revert this

2024-03-30 19:56 UTC, bartekpacia commented on packages/location/lib/location.dart
> +    bool? pausesLocationUpdatesAutomatically = true,
I don't think `true` is a good default. What's the current behavior?

2024-03-30 19:56 UTC, bartekpacia commented on packages/location/example/ios/Podfile
> +# platform :ios, '12.0'
let's uncomment this line

2024-03-30 19:56 UTC, bartekpacia commented on packages/location/pubspec.yaml
> +    path: ../location_web/
revert these lines

2024-04-01 08:23 UTC, nasif-m4 commented on packages/location/lib/location.dart
> +    bool? pausesLocationUpdatesAutomatically = true,
@bartekpacia 
On supported platforms the default value of this property is true; otherwise the default value is false and is immutable.

https://developer.apple.com/documentation/corelocation/cllocationmanager/1620553-pauseslocationupdatesautomatical

2024-05-06 12:35 UTC, ufoloko commented
on IOS devices, location updates in background are paused automatically depending on activity detected by device, so if you have an app that needs to keep getting locations like a tracking app you need to set this parameter in false.

2024-06-21 08:34 UTC, tanvir-ahmed-m4 commented on packages/location_web/pubspec.yaml
> +    path: ../location_platform_interface/
Reverted.

2024-06-21 08:35 UTC, tanvir-ahmed-m4 commented on packages/location/lib/location.dart
> +    bool? pausesLocationUpdatesAutomatically = true,
The current behaviour is `true` by default.

2024-06-21 08:35 UTC, tanvir-ahmed-m4 commented on packages/location/example/ios/Podfile
> +# platform :ios, '12.0'
Uncommented.

2024-06-21 08:36 UTC, tanvir-ahmed-m4 commented on packages/location/pubspec.yaml
> +    path: ../location_web/
Reverted

2024-06-21 08:40 UTC, tanvir-ahmed-m4 commented
> on IOS devices, location updates in background are paused automatically depending on activity detected by device, so if you have an app that needs to keep getting locations like a tracking app you need to set this parameter in false.

That is exactly our use-case. The app needs to track the location of the user even when the app or the device is not actively used.

2024-06-21 08:42 UTC, tanvir-ahmed-m4 commented on packages/location/example/ios/Podfile
> +# platform :ios, '12.0'
Uncommented

2025-06-12 10:05 UTC, tanvir-ahmed-m4 commented
Hi @bartekpacia , I have rebased the changes and updated tests. Please review.

2025-06-13 14:32 UTC, bartekpacia approved these changes
looks good, i only have some tiny dartdoc suggestions

thank you!

2025-06-13 14:32 UTC, bartekpacia commented on packages/location/lib/location.dart
> +  /// location-manager object may pause location updates.
```suggestion
  /// underlying location manager object may pause location updates.
```

2025-06-13 14:32 UTC, bartekpacia commented on packages/location_platform_interface/lib/location_platform_interface.dart
> +  /// location-manager object may pause location updates.
```suggestion
  /// underlying location manager object may pause location updates.
```

2025-06-13 14:32 UTC, bartekpacia commented on packages/location_platform_interface/lib/src/method_channel_location.dart
> +  /// location-manager object may pause location updates.
```suggestion
  /// underlying location manager object may pause location updates.
```

2025-06-17 08:11 UTC, nasif-m4 approved these changes

2025-06-17 12:55 UTC, merged